name: Build Windows Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Create firebase_options.dart
      run: |
        New-Item -ItemType Directory -Force -Path lib
        Set-Content -Path lib\firebase_options.dart -Value $env:FIREBASE_OPTIONS_DATA
      env:
        FIREBASE_OPTIONS_DATA: ${{ secrets.FIREBASE_OPTIONS_DART }}

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows app
      run: flutter build windows --release

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Estinol-Editor-2-Windows
        path: build\windows\x64\runner\Release\